# Generated by Django 5.0.1 on 2024-06-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_realtor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Realtor',
        ),
    ]
