# Generated by Django 5.0.1 on 2024-06-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
    ]
