# Generated by Django 5.2.1 on 2025-07-23 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_enquiry'),
        ('realtors', '0006_realtor_is_mvp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='phone',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='realtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtor_enquiries', to='realtors.realtor'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='listings.listing'),
        ),
    ]
