# Generated by Django 5.2.1 on 2025-07-23 06:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_enquiry_email_remove_enquiry_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
