# Generated by Django 5.2.1 on 2025-07-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_enquiry_contact_date_alter_enquiry_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
