# Generated by Django 5.2.1 on 2025-07-10 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='realtors/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_realtor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
