# Generated by Django 5.0.1 on 2024-07-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_remove_realtor_group_realtor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
