# Generated by Django 5.2.1 on 2025-07-10 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_alter_realtor_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtors_realtor', to=settings.AUTH_USER_MODEL),
        ),
    ]
